### ISSUE TITLE
nimgui sample fails

### ISSUE THREAD

**Issue by melMass** [lmariscal/nimgl#17]
Hello when trying to compile the imgui sample I have the following error:

```ruby
.nimble/pkgs/nimgl-0.3.5/nimgl/imgui.nim(422, 13) Error: invalid pragma: unchecked
```

Thanks for the lib

**Comment by lmariscal** [comment]
Hi, what version of nimgl and nim are you using? This could have something to do with #12

**Comment by melMass** [comment]
Thanks, it seems related yes.

```ruby
Nim Compiler Version 0.19.9 [MacOSX: amd64]
nimgl-0.3.5
```

**Comment by lmariscal** [comment]
My bad, I didn't changed the generator with the previous fix, will be pushing an update to the generator too.
Also, does 0.19.9 breaks OpenGL GLenums for you?

**Comment by melMass** [comment]
A few hours ago I could build gree_window as following and it worked:

```bash
nim c -r -d:glfwStaticLib src/bin/green_win.nim
```

but now it throws:
```ruby
.nimble/pkgs/nimgl-0.3.5/nimgl/opengl.nim(361, 38) Error: -2 can't be converted to GLenum
```

**Comment by melMass** [comment]
But the previous error is gone 👍

**Comment by lmariscal** [comment]
Hmm, that is really weird, will look into the changes that are in the nightly version of nim.
