### ISSUE TITLE
-2 can't be converted to GLenum

### ISSUE THREAD

**Issue by slugmatt** [lmariscal/nimgl#18]
Getting this error with nim devel, works after commenting out lines 361 - 365 in opengl.nim, trying to make GLenum(uint32) from negative value.
```
GL_NEXT_BUFFER_NV*: GLenum = GLenum(-2)
GL_SKIP_COMPONENTS4_NV*: GLenum = GLenum(-3)
GL_SKIP_COMPONENTS3_NV*: GLenum = GLenum(-4)
GL_SKIP_COMPONENTS2_NV*: GLenum = GLenum(-5)
GL_SKIP_COMPONENTS1_NV*: GLenum = GLenum(-6)
```

**Comment by lmariscal** [comment]
https://raw.githubusercontent.com/KhronosGroup/OpenGL-Registry/master/xml/gl.xml
```
<enums namespace="GL" group="TransformFeedbackTokenNV" vendor="NV" comment="For NV_transform_feedback. No clue why small negative values are used">
  <enum value="-2" name="GL_NEXT_BUFFER_NV"/>
  <enum value="-3" name="GL_SKIP_COMPONENTS4_NV"/>
  <enum value="-4" name="GL_SKIP_COMPONENTS3_NV"/>
  <enum value="-5" name="GL_SKIP_COMPONENTS2_NV"/>
  <enum value="-6" name="GL_SKIP_COMPONENTS1_NV"/>
</enums>
```

Have to say that I love this comment.... Will have to research some more.

**Comment by lmariscal** [comment]
Will be removing those constants from the bindings. Extensions are still a pretty much WIP at the moment, will be looking at them in the future.

Reading https://www.khronos.org/registry/OpenGL/extensions/NV/NV_transform_feedback.txt it's pretty much safe to remove them.
