### ISSUE TITLE
cimgui -d:imguiSrc=1 is broken

### ISSUE THREAD

**Issue by GoogleBot42** [lmariscal/nimgl#19]
_This is a technically two issues... the first is trivial to fix._

**The trivial issue**
Attempting to compile the included cimgui example using `-d:imguiSrc=1` fails.  (My understanding is this bakes cimgui into the exe so there is no need to have a shared lib)
```
> nim c -d:imguiSrc=1 timgui.nim
...
Error: unhandled exception: cannot open: private/cimgui/cimgui/cimgui.cpp [IOError]
```
This is because the path is not quite correct.  Correcting [this](https://github.com/lmariscal/nimgl/blob/c639e0a800e17916f8b5d98da22b6118b5e9e822/src/nimgl/imgui.nim#L46) line to `private/cimgui/cimgui.cpp` fixes the trivial issue.

**Second issue**
Try to compile again with the above fix, and you get errors like this
```
Error: execution of an external compiler program 'gcc -c  -w -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -I/home/jeremy/Programming/nim/nimgl/src/nimgl/private/cimgui -DCIMGUI_DEFINE_ENUMS_AND_STRUCTS -DSTB_IMAGE_IMPLEMENTATION -I/home/jeremy/Programming/nim/nimgl/src/nimgl/stb/../private/stb -D_GLFW_X11 -g3 -O0  -I/usr/share/nim -o /home/jeremy/.cache/nim/timgui_d/nimgl_timgui.c.o /home/jeremy/.cache/nim/timgui_d/nimgl_timgui.c' failed with exit code: 1

In file included from /home/jeremy/.cache/nim/timgui_d/nimgl_timgui.c:10:
/home/jeremy/Programming/nim/nimgl/src/nimgl/imgui.nim:1653:15: error: conflicting types for ‘igShowDemoWindow’
 1653 | proc igShowDemoWindow*(p_open: ptr bool = nil): void {.imgui_lib, importc: "igShowDemoWindow".}
      |               ^~~~~~~~~~~~~~~~
/usr/share/nim/nimbase.h:186:44: note: in definition of macro ‘N_CDECL’
  186 | #    define N_CDECL(rettype, name) rettype name
      |                                            ^~~~
In file included from /home/jeremy/.cache/nim/timgui_d/nimgl_timgui.c:12:
/home/jeremy/Programming/nim/nimgl/src/nimgl/private/cimgui/cimgui.h:939:17: note: previous declaration of ‘igShowDemoWindow’ was here
  939 | CIMGUI_API void igShowDemoWindow(bool* p_open);
      |                 ^~~~~~~~~~~~~~~~

```
I'm not entirely sure what is going so I'm not going to try and guess.  I'm pretty new to nim.   I hope this can be resolved though.  Thanks.

**Comment by lmariscal** [comment]
The first issue with cimgui is that the cimgui.cpp file change path and I forgot to also change it in the binding generation.
The second issue is a little more tricky, I'm kinda the maintainer of both nimgui and nimgl, when zacharycarter forked the nimgui repo I mentioned to him https://github.com/lmariscal/nimgl_gen/issues/1#issuecomment-443444236 that the cpp compilation is not working correctly. The issue boils down to namespace conflicts and some other non persistent values in the json generated by cimgui.
This issue will take me longer since I will most likely have to fix it through some trial and error with the cpp compiler.

After I fix it, I will push both changes. Will let you know any progress.

**Comment by lmariscal** [comment]
What I recommend is that you only use the C compiler, you can compile the [cimgui](https://github.com/cimgui/cimgui) dll and copy it to the same path as your binary, some other info in the [imgui.nim file](https://github.com/lmariscal/nimgl/blob/master/src/nimgl/imgui.nim).
If you need to use the C++ compiler do to some other libs, this issue needs to be solved first though.

**Comment by GoogleBot42** [comment]
Glad to know this is a known issue.  I hope you it can be resolved but I understand that might take time if it does happen.  I've now tried compiling with nim's c++ backend too but it had a similar error.  So both the c and c++ backends don't work for `-d:imguiSrc=1`.  For now, I'll use the shared lib.  Thanks.

For context, I was hoping to use imgui in emscripten and compiling into a single executable would be more convenient.

**Comment by lmariscal** [comment]
Was able to fix the issues related to conflicting declarations and other misc conflicting types that only occur in C++. There might be other conflicts that I was not able to replicate while compiling in C++ so let me know if you experience any other issue. Will be pushing a new release.
