### ISSUE TITLE
Example Broken

### ISSUE THREAD

**Issue by rafaelvasco** [lmariscal/nimgl#5]
Trying to compile the front page green screen example results in :

 Error: expression 'setKeyCallback(w, keyProc)' has no type (or is ambiguous)

With latest Nim (0.19)

**Comment by lmariscal** [comment]
First of all sorry for the delay.
The example in the readme was made for the current head version where setKeyCallback returns a pointer to the previous proc used to managed the event. If you want to fix the issue with v0.2.1 just remove the discard statement.
Pushing a v0.2.2 tag to clear this issue. Thanks for the notice!
